import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
// 👇 Import Services
import { PaperService } from '../../../services/paper';
import { ReviewService } from '../../../services/review';
import { AuthService } from '../../../services/auth';

@Component({
  selector: 'app-grading',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './grading.html',
  styleUrl: './grading.css'
})
export class Grading implements OnInit {

  paperId: any;
  paper: any = null;
  currentUser: any = {};

  // ✨ New Flag: Determines if the form is in Read-Only mode (View History)
  isReadOnly: boolean = false;

  // Form Data
  scoreCriteria: any = {
    originality: 0,
    relevance: 0,
    quality: 0,
    presentation: 0
  };
  comments: string = '';
  recommendation: string = 'Accept';

  // Helper to calculate total
  get totalScore(): number {
    return this.scoreCriteria.originality +
      this.scoreCriteria.relevance +
      this.scoreCriteria.quality +
      this.scoreCriteria.presentation;
  }

  constructor(
    private route: ActivatedRoute,
    private router: Router,
    private paperService: PaperService,   // 👈 Inject PaperService
    private reviewService: ReviewService, // 👈 Inject ReviewService
    private authService: AuthService      // 👈 Inject AuthService
  ) {}

  ngOnInit() {
    this.paperId = this.route.snapshot.paramMap.get('id');

    // Get Current User (Reviewer) from AuthService
    const user = this.authService.getLoggedUser();
    if (user) {
      this.currentUser = user;
    } else {
      // Safety check: redirect if not logged in
      this.router.navigate(['/login']);
    }

    this.loadPaper();
    this.checkForExistingReview(); // 👈 Check if this paper was already graded
  }

  loadPaper() {
    // Find paper by ID using Service
    if (this.paperId) {
      this.paperService.getPaperById(this.paperId).subscribe((data: any) => {
        this.paper = data;
      });
    }
  }

  // ✨ Logic to populate form if viewing history
  checkForExistingReview() {
    this.reviewService.getAllReviews().subscribe((allReviews: any[]) => {
      // Find a review that matches this Paper ID AND this Reviewer's Email
      const existingReview = allReviews.find((r: any) =>
        String(r.paperId) === String(this.paperId) &&
        r.reviewerEmail === this.currentUser.email
      );

      if (existingReview) {
        // ✅ Found previous review: Enable Read-Only Mode
        this.isReadOnly = true;

        // ✅ Populate Form Data
        this.scoreCriteria = existingReview.breakdown;
        this.comments = existingReview.comments;
        this.recommendation = existingReview.recommendation;
      }
    });
  }

  submitReview() {
    // Prevent submission if in Read-Only mode
    if (this.isReadOnly) return;

    // 1. Validation
    if (this.totalScore === 0) {
      alert("Please score the paper before submitting.");
      return;
    }

    // 2. Create Review Object
    const newReview = {
      // id will be generated by Service
      paperId: this.paperId,
      reviewerEmail: this.currentUser.email,
      score: this.totalScore,
      breakdown: this.scoreCriteria,
      recommendation: this.recommendation,
      comments: this.comments,
      date: new Date()
    };

    // 3. Submit Review using ReviewService
    this.reviewService.submitReview(newReview).subscribe((res: any) => {

      if (res.success) {
        // 4. Update Paper Status to 'Reviewed' using PaperService
        if (this.paper) {
          this.paper.status = 'Reviewed';
          this.paperService.updatePaper(this.paper).subscribe(() => {
            // 5. Success & Redirect
            alert("✅ Review Submitted Successfully!");
            this.router.navigate(['/dashboard/review-history']);
          });
        }
      } else {
        alert(res.message); // Handle duplicate review error
      }
    });
  }

  cancel() {
    // Redirect logic based on mode
    if (this.isReadOnly) {
      this.router.navigate(['/dashboard/review-history']); // Go back to History
    } else {
      this.router.navigate(['/dashboard/reviews']); // Go back to Pending list
    }
  }
}
